FROM ubuntu

RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential gcc clang gdb git make \
    tar gzip unzip \
    wget curl ca-certificates

